services:
  web:
    build: .
    container_name: fastapi_app
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    restart: always
    command: >
      gunicorn app.main:app
      -k uvicorn.workers.UvicornWorker
      --bind 0.0.0.0:8000
      --workers 4
